### ISSUE TITLE
This role is unusable with 5.x

### ISSUE THREAD

**Issue by emanuelis** [nodesource/ansible-nodejs-role#28]
:(

**Comment by wolfeidau** [comment]
Can you elaborate?

**Comment by emanuelis** [comment]
`debian_repo_version: "{{ nodejs_version if '4' not in nodejs_version else '4.x' }}"`

"5.x" is unsupported in this ansible role.

**Comment by nbering** [comment]
I got it working like this:
```
---
- name: Node Test Role
  hosts: all
  become: yes
  become_method: sudo
  roles:
  - { role: nodesource.node, nodejs_version: "6", debian_repo_version: "6.x" }
```
